// Generated by sidecrew (src/verifier/ts.ts). Scoped to one file — see ADR-0004.
/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
export default {
  testRunner: "vitest",
  // The type checker is what keeps mutants that cannot compile out of the denominator: they are noise
  // about TypeScript, not evidence about the test. It only does that with disableTypeChecks off.
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.json",
  disableTypeChecks: false,
  coverageAnalysis: "perTest",
  reporters: ["json"],
  jsonReporter: { fileName: "reports/mutation/mutation.json" },
  mutate: ["src/**/*.ts"],
  // Safe only because the sandbox is per candidate, so this file is always cold. Pointed at a shared
  // location it silently hands one candidate the kills another candidate earned — measured, ADR-0004.
  incremental: true,
  incrementalFile: "reports/stryker-incremental.json",
  concurrency: 2,
  // A score is a signal for review, never a pass/fail — ADR-0006. Nothing here may fail the run.
  thresholds: { high: 80, low: 60, break: null },
  timeoutMS: 10000,
  logLevel: "warn",
};
