#!/bin/sh
# Generated by sidecrew (src/verifier/swift.ts). Run by Muter once per mutant. See ADR-0005.
set -m
timeout_s=${SIDECREW_MUTANT_TIMEOUT_S:-60}
log=$(mktemp -t sidecrew-swift) || exit 70

"$@" >"$log" 2>&1 &
child=$!
(
  sleep "$timeout_s"
  # By path first, then by process group. SwiftPM runs the built xctest binary in a process group of
  # its own, so the group kill below reaches xcrun and swift-test and leaves the thing that is actually
  # hung spinning for ever with PPID 1. Muter gives each mutant its own <sandbox>_mutated copy, so
  # every process in this tree names $PWD and nothing else on the machine does.
  pkill -9 -f "$PWD" 2>/dev/null
  kill -9 -"$child" 2>/dev/null
) 2>/dev/null &
watchdog=$!
set +m
wait "$child" 2>/dev/null
code=$?
kill -9 "$watchdog" 2>/dev/null
wait "$watchdog" 2>/dev/null

cat "$log"
# Muter looks for XCTest's "with <n> failure" to call a mutant killed. Swift Testing never prints it, so
# without this line every Swift Testing kill is reported as a runtime error instead. Gated on the run
# actually having reported failures: a crash or a timeout must keep reading as a runtime error.
if grep -q 'Test run with .* failed' "$log"; then
  echo "sidecrew: the Swift Testing run failed. Executed 1 tests, with 1 failure."
fi
rm -f "$log"
exit "$code"
