// What is the exemplar worth, and what are the shape rules worth on top of it?
//
//   npm run measure:prompt-ablation
//
// Research §B says human-written exemplars are what make a small model usable on this task, and the
// whole planner phase is built on that claim. It is somebody else's measurement, on somebody else's
// models. This is ours: three prompts, the same twenty tasks, the same worker, the same seed, the same
// verifier, and the only thing that varies is the wording.
//
// Held constant, deliberately and in this order of importance:
//
//   * **The tasks.** Every variant gets the identical `WorkerTask`s, built once from the four plans.
//   * **The seed and the temperature.** `RUN_SEED`, temperature 0 — so a rerun is comparable with this
//     one, which is the only thing that makes a two-point difference worth reading (ADR-0003).
//   * **`imports_hint`.** It survives into the bare variant even though nothing else does. Dropping it
//     would make the bare row a measurement of whether a 7B can guess our module resolution, and the
//     fixture chose `Bundler` over `NodeNext` to avoid exactly that (fixtures/ts-fixture/README.md).
//   * **No retry.** This measures the first attempt. The retry is a separate mechanism with its own
//     evidence (TestPilot, research §B) and folding it in here would hide which one did the work.
//
// The funnel is reported per variant, not just the survival rate, because "the exemplar helps" and
// "the exemplar stops it failing to compile" are different claims and the second is the interesting one.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { hostname } from "node:os";
import { discoverWorkers, generate, portsFromEnv, RUN_SEED } from "../src/batch.js";
import { readMemory } from "../src/doctor.js";
import { buildTasks, loadPlan, functionOfTaskId, verifyCandidate, type LoadedPlan } from "../src/plan.js";
import { run } from "../src/exec.js";
import type { Verdict, WorkerTask } from "../src/schemas.js";

const PLANS = ["strings", "numbers", "arrays", "async"].map((m) => `fixtures/ts-fixture/plans/${m}/test_plan.json`);

const VARIANTS = [
  { id: "bare", file: "experiments/prompt-ablation/variants/bare.md", has: "function source + imports_hint" },
  // Not one of the three the phase asked for. Added after the fact, because every one of bare's 15
  // compile failures was the same missing line — `import { describe, it, expect } from "vitest"` — and
  // without this row "the exemplar is worth 55 points" is really "the exemplar happens to contain an
  // import we never asked for". This is the row that separates the two claims.
  { id: "bare+import", file: "experiments/prompt-ablation/variants/bare-import.md", has: "bare + one sentence telling it to import the test framework" },
  { id: "exemplar", file: "experiments/prompt-ablation/variants/exemplar.md", has: "bare + the shape's exemplar file" },
  { id: "exemplar+rules", file: "experiments/prompt-ablation/variants/exemplar-rules.md", has: "exemplar + the shape kind and its rules" },
] as const;

const RESULTS = "experiments/go-no-go/results";

/**
 * Where the raw candidates go, one file per variant × task.
 *
 * Not in the results JSON — they are worker output and `BatchResult`'s rule about not handing that to
 * Claude applies to the spirit of a results file too. But they are kept, because Phase 4's most
 * expensive hour was a funnel that looked like a model failure and was a serving detail, and a compile
 * column nobody can look behind is exactly that shape. Generation is deterministic at a fixed seed, so
 * these can also be regenerated byte-for-byte.
 */
const CANDIDATES = "experiments/prompt-ablation/candidates";

interface Outcome {
  task_id: string;
  survived: boolean;
  stage_reached: string;
  compile_ok: boolean;
  pass_ok: boolean;
  tautological: boolean;
  killed: number;
  mutation_score: number | null;
  completion_tokens: number;
  generate_ms: number;
  verify_ms: number;
}

const quantile = (values: number[], q: number): number => {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.min(sorted.length - 1, Math.max(0, Math.ceil(q * sorted.length) - 1))] ?? 0;
};

const say = (line: string): void => { process.stderr.write(`${line}\n`); };

/** `swift`, `sw_vers`, `mlx_lm --version` — whatever makes the numbers attributable to a machine. */
const version = async (cmd: string, args: string[]): Promise<string> => {
  try {
    const r = await run(cmd, args, { timeoutMs: 20_000 });
    return `${r.stdout}${r.stderr}`.trim().split("\n")[0] ?? "";
  } catch {
    return "unknown";
  }
};

/**
 * `--only bare` reruns one variant. Generation is deterministic at a fixed seed, so a rerun reproduces
 * the same candidates byte for byte — which is how a surprising column gets looked behind without
 * paying for the other two variants again.
 */
const only = (() => {
  const at = process.argv.indexOf("--only");
  return at === -1 ? undefined : process.argv[at + 1];
})();

async function main(): Promise<void> {
  const loaded: LoadedPlan[] = [];
  const tasks: { task: WorkerTask; plan: LoadedPlan }[] = [];
  for (const path of PLANS) {
    const plan = await loadPlan(path);
    loaded.push(plan);
    for (const task of buildTasks(plan)) tasks.push({ task, plan });
  }
  say(`${tasks.length} tasks over ${loaded.length} plans and ${loaded.reduce((n, l) => n + l.plan.functions.length, 0)} functions`);

  const workers = await discoverWorkers(portsFromEnv());
  const worker = workers[0];
  if (worker === undefined) throw new Error("no local worker is answering — start one with: sidecrew serve");
  say(`worker ${worker.model} @ ${worker.revision.slice(0, 12) || "unpinned"} on ${worker.baseUrl}`);

  const mem = await readMemory();
  const variants: Record<string, unknown>[] = [];

  for (const variant of VARIANTS) {
    if (only !== undefined && variant.id !== only) continue;
    const template = await readFile(variant.file, "utf8");
    await mkdir(`${CANDIDATES}/${variant.id.replace("+", "-")}`, { recursive: true });
    const outcomes: Outcome[] = [];
    say(`\n── ${variant.id} ──`);

    for (const { task, plan } of tasks) {
      const t0 = performance.now();
      const candidate = await generate(task, worker, { template });
      const t1 = performance.now();
      // Concurrency 1: the ablation is a comparison, and a Stryker run that shares cores with itself
      // differently between variants would put noise into the one column being read.
      const verdict: Verdict = await verifyCandidate(plan, candidate, functionOfTaskId(task.task_id), { concurrency: 1 });
      const t2 = performance.now();

      outcomes.push({
        task_id: task.task_id,
        survived: verdict.survived,
        stage_reached: verdict.stage_reached,
        compile_ok: verdict.compile_ok,
        pass_ok: verdict.pass_ok,
        tautological: verdict.tautological,
        killed: verdict.mutation?.killed ?? 0,
        mutation_score: verdict.mutation?.score ?? null,
        completion_tokens: candidate.usage.completion_tokens,
        generate_ms: Math.round(t1 - t0),
        verify_ms: Math.round(t2 - t1),
      });
      await writeFile(
        `${CANDIDATES}/${variant.id.replace("+", "-")}/${task.task_id.replace(/[^\w.-]+/g, ".")}.test.ts`,
        candidate.test_source,
        "utf8",
      );
      say(`  ${verdict.survived ? "survived" : `failed at ${verdict.stage_reached}`.padEnd(8)}  ${task.task_id}`);
    }

    const survivors = outcomes.filter((o) => o.survived);
    const latencies = outcomes.map((o) => o.generate_ms + o.verify_ms);
    variants.push({
      id: variant.id,
      // Per variant rather than per file: `--only` merges a row measured later into a file the other
      // rows were written to, and a single top-level date would then be wrong for one of them.
      measured_at: new Date().toISOString(),
      prompt: variant.file,
      contains: variant.has,
      tasks: outcomes.length,
      survived: survivors.length,
      survival_rate: Number((survivors.length / outcomes.length).toFixed(3)),
      funnel: {
        compiled: outcomes.filter((o) => o.compile_ok).length,
        passed: outcomes.filter((o) => o.pass_ok).length,
        killed_ge_1: outcomes.filter((o) => o.killed >= 1).length,
        non_tautological: outcomes.filter((o) => !o.tautological).length,
      },
      median_mutation_score_of_survivors: survivors.length === 0
        ? null
        : Number(quantile(survivors.map((o) => o.mutation_score ?? 0), 0.5).toFixed(3)),
      latency_ms: { median: quantile(latencies, 0.5), p90: quantile(latencies, 0.9) },
      generate_ms: { median: quantile(outcomes.map((o) => o.generate_ms), 0.5) },
      verify_ms: { median: quantile(outcomes.map((o) => o.verify_ms), 0.5) },
      median_completion_tokens: quantile(outcomes.map((o) => o.completion_tokens), 0.5),
      outcomes,
    });
  }

  const date = new Date().toISOString().slice(0, 10);
  const path = `${RESULTS}/prompt-ablation-${date}.json`;

  // `--only` merges its one row into the file the others are already in, in the declared variant order,
  // and touches nothing else. Rerunning all three to add a fourth row would be an hour spent
  // regenerating identical output — generation is deterministic, which is the point of the seed.
  if (only !== undefined) {
    const existing = JSON.parse(await readFile(path, "utf8")) as { variants: { id: string }[] };
    const order: string[] = VARIANTS.map((v) => v.id);
    const at = (row: unknown): number => order.indexOf(String((row as { id?: unknown }).id ?? ""));
    const merged = [...existing.variants.filter((v) => v.id !== only), ...variants].sort((a, b) => at(a) - at(b));
    await writeFile(path, `${JSON.stringify({ ...existing, variants: merged }, null, 2)}\n`, "utf8");
    say(`\n--only ${only}: merged into ${path}; candidates in ${CANDIDATES}/${only.replace("+", "-")}/`);
    return;
  }

  const result = {
    measured: true,
    experiment: "prompt-ablation",
    date: new Date().toISOString(),
    machine: {
      host: hostname(),
      total_gb: mem?.total_gb ?? null,
      free_gb_at_start: mem?.free_gb ?? null,
      macos: await version("sw_vers", ["-productVersion"]),
      node: process.version,
      mlx_lm: await version("python3", ["-c", "import mlx_lm; print(mlx_lm.__version__)"]),
      xcode_open: null,
    },
    worker: { kind: "local", model: worker.model, revision: worker.revision, temperature: 0, seed: RUN_SEED },
    // In the file, not only in the changelog: a JSON of four survival rates read on its own is exactly
    // the artefact that would get quoted as "exemplars are worth 13 points".
    caveats: [
      "bare's 15 compile failures are one systematic omission: no `import { describe, it, expect } from \"vitest\"`. Exactly the 5 candidates that had it are the 5 that compiled. The bare row measures a convention nobody told the model about, not its ability to write a test.",
      "bare+import is that one sentence and nothing else, and it scores 16/20 — one *above* the full exemplar. On this fixture the exemplar's contribution to survival, once the framework import is stated, is zero (ADR-0017).",
      "16 / 15 / 17 across bare+import / exemplar / exemplar+rules is one or two tasks at n = 1 per cell, one seed, one model, one fixture. Not a ranking. The only large effect here is bare → anything that mentions the import.",
      "the fixture is 14 small pure functions with no mocks, no setup and no lifecycle — the case where a 7B needs the least structural guidance. This says nothing about what an exemplar is worth on real code.",
      "truncate:boundary fails the pass stage in every variant: the fixture's planted off-by-one means a correct boundary assertion is false against the source. It is a constant, not a difference between variants.",
    ],
    held_constant: [
      "the same 20 WorkerTasks, built once from the four plans and reused for every variant",
      `seed ${RUN_SEED}, temperature 0`,
      "imports_hint, which is in the bare variant too — without it the bare row would measure module resolution",
      "verifier concurrency 1",
      "no retry: this is first-attempt survival",
    ],
    plans: loaded.map((l) => ({
      plan: l.planPath.replace(`${process.cwd()}/`, ""),
      module: l.plan.module,
      functions: l.plan.functions.length,
      tasks: l.plan.functions.reduce((n, f) => n + f.shapes.length, 0),
      shapes: l.plan.shapes.map((s) => s.kind),
      exemplar_function: l.plan.shapes[0]?.exemplar_function ?? null,
      planner_tokens: l.plan.meta.planner_tokens,
    })),
    variants,
  };

  await mkdir(RESULTS, { recursive: true });
  await writeFile(path, `${JSON.stringify(result, null, 2)}\n`, "utf8");

  say("\n── result ──");
  for (const v of variants as { id: string; survived: number; tasks: number; funnel: Record<string, number>; latency_ms: { median: number } }[]) {
    say(`${v.id.padEnd(15)} ${v.survived}/${v.tasks}  compiled ${v.funnel.compiled} → passed ${v.funnel.passed} → killed≥1 ${v.funnel.killed_ge_1} → non-taut ${v.funnel.non_tautological}  ${v.latency_ms.median} ms median`);
  }
  say(`wrote ${path}`);
}

main().catch((e) => {
  process.stderr.write(`${String((e as Error)?.stack ?? e)}\n`);
  process.exit(1);
});
