// `sidecrew mcp` — the stdio MCP server Claude Code launches.
//
// Ten tools, and the same ten functions the CLI calls; nothing here has logic of its own beyond
// turning an exception into a message a model can act on. The input schemas are the contract's own
// zod schemas (`src/schemas.ts`), so a tool cannot accept something the pipeline would later refuse.
//
// The descriptions say "on this machine" and "no Claude tokens" in as many words on purpose. A model
// deciding between this tool and writing the test itself is making a cost decision, and the only way
// it can make that decision correctly is if the cost is in the description (ADR-0001: workers are not
// subagents, and cannot be).
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { generate, runBatch, discoverWorkers, portsFromEnv } from "./batch.js";
import { changeEscalationBatch, escalationBatch } from "./escalate.js";
import { validateChangePlan } from "./fix-validate.js";
import { runFix } from "./fix.js";
import { reviewQueueFor } from "./run.js";
import { loadPlan, verifyCandidate, functionOfTaskId } from "./plan.js";
import { Candidate, WorkerTask } from "./schemas.js";
import { statusReport } from "./status.js";
import { validatePlan } from "./validate.js";

export const SERVER_VERSION = "0.0.2";

/** Every tool answers with JSON text, and an exception answers with the sentence that explains it. */
type ToolResult = { content: { type: "text"; text: string }[]; isError?: boolean };

const ok = (value: unknown): ToolResult => ({ content: [{ type: "text", text: JSON.stringify(value, null, 2) }] });

const failed = (e: unknown): ToolResult => ({
  content: [{ type: "text", text: String((e as Error)?.message ?? e) }],
  isError: true,
});

const answer = async (f: () => Promise<unknown>): Promise<ToolResult> => {
  try {
    return ok(await f());
  } catch (e) {
    return failed(e);
  }
};

export function buildServer(): McpServer {
  const server = new McpServer({ name: "sidecrew", version: SERVER_VERSION });

  server.tool(
    "sidecrew_status",
    "Is a local worker up, which model and revision it is serving, free RAM, and which verifier tools " +
      "this project has. Call it before a run: everything else here needs a worker, and a missing " +
      "stryker or muter is why a verdict would fail for a reason that is not the test's fault.",
    {
      port: z.number().int().positive().optional().describe("worker port; default 8000"),
      project: z.string().optional().describe("the project being verified — tsc/vitest/stryker are reported from its node_modules, not sidecrew's"),
    },
    async ({ port, project }) => answer(() => statusReport({ port, project })),
  );

  server.tool(
    "sidecrew_generate",
    "One WorkerTask -> one candidate test, generated by the MLX model running on this machine. " +
      "Costs zero Claude tokens and touches no network: it is an HTTP call to http://localhost:<port>/v1. " +
      "Raw worker output — verify it before showing it to anyone.",
    { task: WorkerTask.describe("the task, as docs/specs/pipeline.md defines it") },
    async ({ task }) => answer(async () => {
      const workers = await discoverWorkers(portsFromEnv());
      const worker = workers[0];
      if (worker === undefined) throw new Error("no local worker is answering — start one with: sidecrew serve");
      return generate(task, worker);
    }),
  );

  server.tool(
    "sidecrew_verify",
    "compile -> run -> mutate one candidate against the function its task_id names, and return a Verdict. " +
      "Survive means it compiled, passed against the unmodified source, killed at least one mutant of " +
      "that function, and was not tautological. Runs entirely on this machine.",
    {
      candidate: Candidate.describe("what a worker produced, or a hand-written test in the same shape"),
      plan_path: z.string().describe("path to the test_plan.json the candidate was generated from"),
      function_name: z.string().optional().describe("defaults to the part of task_id before the first colon"),
      test_target: z.string().optional().describe("Swift only: the test target under Tests/ (ADR-0014), overriding the plan"),
    },
    async ({ candidate, plan_path, function_name, test_target }) => answer(async () => {
      const loaded = await loadPlan(plan_path);
      return verifyCandidate(loaded, candidate, function_name ?? functionOfTaskId(candidate.task_id), { testTarget: test_target });
    }),
  );

  server.tool(
    "sidecrew_run_batch",
    "Run a whole plan on this machine: for every function x shape, generate -> verify -> retry once " +
      "with the error appended -> escalate. Generation is local and costs zero Claude tokens; only the " +
      "BatchResult comes back, so you see survivors and escalations rather than raw worker output. " +
      "Minutes, not seconds — roughly 10 s per TypeScript candidate and 40 s per Swift one.",
    {
      plan_path: z.string().describe("path to test_plan.json"),
      concurrency: z.number().int().positive().optional().describe("candidates in flight; a ceiling, lowered when free RAM says so"),
      dry_run: z.boolean().optional().describe("write the tasks and report the concurrency, then stop before the first token"),
      test_target: z.string().optional().describe("Swift only: the test target under Tests/ (ADR-0014), overriding the plan"),
    },
    async ({ plan_path, concurrency, dry_run, test_target }) =>
      answer(() => runBatch(plan_path, { concurrency, dryRun: dry_run, testTarget: test_target })),
  );

  server.tool(
    "sidecrew_plan_validate",
    "Check a test_plan.json before a run spends anything on it: it parses, its module and exemplars are " +
      "on disk, every line range really is the function it names, and — unless verify_exemplars is false — " +
      "every exemplar survives the verifier. Call it after writing or editing a plan. Verifying the " +
      "exemplars is the expensive half: one verdict per shape, seconds on TypeScript and tens of seconds " +
      "on Swift. A stale source_sha is a warning here and a refusal in sidecrew_run_batch.",
    {
      plan_path: z.string().describe("path to test_plan.json"),
      verify_exemplars: z.boolean().optional().describe("default true; false is the fast structural pass, and the report warns that it was used"),
    },
    async ({ plan_path, verify_exemplars }) =>
      answer(() => validatePlan(plan_path, { verifyExemplars: verify_exemplars })),
  );

  server.tool(
    "sidecrew_escalate",
    "What the local workers could not do, assembled for you to write yourself. Reads " +
      ".sidecrew/runs/<id>/escalations.jsonl and returns each failed task with the exemplar and rules the " +
      "worker had, plus both attempts' errors. Costs no worker tokens — it reads a finished run off disk. " +
      "Two failures in here are NOT the test's fault and must not be rewritten as though they were: a " +
      "stage_reached of 'mutation' means the mutation tool broke, and four mutation counts of zero mean " +
      "nothing in that function could be mutated.",
    {
      run_id: z.string().optional().describe("defaults to the most recent run under .sidecrew/runs"),
      dir: z.string().optional().describe("where runs/ lives; default .sidecrew"),
      model: z.string().optional().describe("recorded as suggested_model; sonnet unless you say otherwise"),
    },
    async ({ run_id, dir, model }) => answer(() => escalationBatch(run_id, { dir, model })),
  );

  server.tool(
    "sidecrew_review",
    "Which survivors are worth reading, and in what batches. Survival is a filter, not an endorsement — " +
      "a test that pins today's wrong answer kills every mutant — so this returns survivors below the " +
      "mutation-score threshold plus a deterministic audit sample of the rest, batched under a token cap. " +
      "The threshold is per language and defaults accordingly: a Swift score is computed over one or two " +
      "mutants against TypeScript's six to twelve. Reads a finished run off disk; no worker tokens.",
    {
      run_id: z.string().optional().describe("defaults to the most recent run under .sidecrew/runs"),
      dir: z.string().optional().describe("where runs/ lives; default .sidecrew"),
      threshold: z.number().min(0).max(1).optional().describe("overrides the per-language default (0.6 TypeScript, 1.0 Swift)"),
      audit_fraction: z.number().min(0).max(1).optional().describe("of the survivors above the threshold; default 0.1"),
      max_batch_tokens: z.number().int().positive().optional().describe("estimated input tokens per batch; default 12000"),
    },
    async ({ run_id, dir, threshold, audit_fraction, max_batch_tokens }) =>
      answer(() => reviewQueueFor({ runId: run_id, dir, threshold, auditFraction: audit_fraction, maxBatchTokens: max_batch_tokens })),
  );

  // ── workload #2a (Phase 12) ─────────────────────────────────────────────────────────────────────
  //
  // `BACKLOG.md` held these back from Phase 10 on purpose: a tool Claude can call is only useful once
  // something writes `ChangePlan`s for it to call with, and adding it earlier would have shipped a tool
  // that went stale before anyone used it. The planner is `claude/agents/change-planner.md`.

  server.tool(
    "sidecrew_fix_plan_validate",
    "Check a change_plan.json before a run spends anything on it, and REFUSE the tasks no worker could " +
      "ever pass: a file too large to return whole (a worker rewrites whole files, so ~8k completion " +
      "tokens is the ceiling), a pre-existing tsc error the ask does not cover (the gate requires zero " +
      "errors in the task's own files, so such a task is unsatisfiable at any temperature), a file " +
      "outside the tsconfig's program, two tasks in one step sharing a file. Call it after writing or " +
      "editing a plan. The expensive half is a real tsc over the project — tens of seconds — and it is " +
      "the half that produces the refusals; compile: false is the fast structural pass. Worth it: the " +
      "gate costs about 262 s per attempt, so one refused task saves nine minutes.",
    {
      plan_path: z.string().describe("path to change_plan.json"),
      compile: z.boolean().optional().describe("default true; false skips tsc and therefore skips the refusals"),
    },
    async ({ plan_path, compile }) => answer(() => validateChangePlan(plan_path, { compile })),
  );

  server.tool(
    "sidecrew_fix",
    "Run a whole change plan on this machine: workload #2a, behaviour-preserving changes — type errors, " +
      "renames, null guards, API migrations, dead code. For each task the local model rewrites the " +
      "listed files whole, and a gate a machine can run decides what you see: the diff stayed confined " +
      "to the task's files, tsc is clean in them with none introduced elsewhere, and every test that " +
      "passed before still passes. Generation is local and costs zero Claude tokens; only the FixResult " +
      "comes back, so you see survivors and escalations rather than raw worker output. " +
      "SLOW — the project's own suite runs per candidate, about 4–5 minutes each, so a 12-task plan is " +
      "roughly an hour. Validate the plan first. Use --dry-run/dry_run to capture the baseline and stop " +
      "before the first token, which is how you find out the tsconfig or the suite is the problem.",
    {
      plan_path: z.string().describe("path to change_plan.json, written by the change-planner agent"),
      concurrency: z.number().int().positive().optional().describe("candidates in flight; a ceiling, lowered when free RAM says so"),
      dry_run: z.boolean().optional().describe("capture the first step's baseline, write the tasks and prompts, then stop"),
      keep_sandbox: z.boolean().optional().describe("leave the sandbox on disk to inspect what the gate actually saw"),
    },
    async ({ plan_path, concurrency, dry_run, keep_sandbox }) =>
      answer(() => runFix(plan_path, { concurrency, dryRun: dry_run, keepSandbox: keep_sandbox })),
  );

  server.tool(
    "sidecrew_fix_escalate",
    "What the local workers could not change, assembled for you to do yourself. Reads a fix run's " +
      "escalations.jsonl and returns each failed task with the files it was given and every attempt's " +
      "verdict — which confinement rule fired, which tsc errors remain, which tests regressed. Costs no " +
      "worker tokens; it reads a finished run off disk. " +
      "TWO of these are NOT the worker's fault and must not be rewritten as though they were: " +
      "machine_failure means the sandbox or the runner broke (exclude it from any rate you quote), and " +
      "a non-null `refused` means the worker said the change cannot be made inside those files — which " +
      "is usually a plan to fix rather than a change to write.",
    {
      run_id: z.string().optional().describe("defaults to the most recent run under .sidecrew/runs"),
      dir: z.string().optional().describe("where runs/ lives; default .sidecrew"),
      model: z.string().optional().describe("recorded as suggested_model; sonnet unless you say otherwise"),
    },
    async ({ run_id, dir, model }) => answer(() => changeEscalationBatch(run_id, { dir, model })),
  );

  return server;
}

export async function runMcp(): Promise<void> {
  await buildServer().connect(new StdioServerTransport());
}
